---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    foreman_installer_scenario: foreman
  roles:
    - role: installer
    - role: installer
      vars:
        foreman_installer_options:
          - '--enable-foreman-plugin-tasks'
