---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    foreman_installer_scenario: foreman
    foreman_installer_verbose: true
    foreman_installer_no_colors: false
  roles:
    - installer
  tasks:
    - name: find tasks config file
      stat:
        path: /etc/foreman/plugins/foreman-tasks.yaml
      register: foreman_tasks_yaml
    - name: check tasks config file exists
      assert:
        that:
          - foreman_tasks_yaml.stat.exists
